import type { INodeProperties } from 'n8n-workflow';

const showOnlyForDocumentTemplateCreate = {
	operation: ['create'],
	resource: ['documentTemplate'],
};

export const documentTemplateCreateDescription: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: showOnlyForDocumentTemplateCreate },
		description: 'Display name of the template',
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'options',
		options: [
			{ name: 'Administrative', value: 7 },
			{ name: 'Credit Note', value: 4 },
			{ name: 'Deposit Invoice', value: 3 },
			{ name: 'Image Rights Consent', value: 6 },
			{ name: 'Invoice', value: 2 },
			{ name: 'Prescription', value: 0 },
			{ name: 'Quote', value: 1 },
			{ name: 'Visit', value: 8 },
		],
		default: 7,
		required: true,
		displayOptions: { show: showOnlyForDocumentTemplateCreate },
		description: 'Document type',
		routing: { send: { type: 'body', property: 'type' } },
	},
	{
		displayName: 'Template (JSON)',
		name: 'template',
		type: 'json',
		default: '{}',
		required: true,
		displayOptions: { show: showOnlyForDocumentTemplateCreate },
		description: 'Template JSON object. Use {} for no template, or {"html": "HTML"} for a stored HTML template.',
		routing: { send: { type: 'body', property: 'template' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: showOnlyForDocumentTemplateCreate },
		options: [
			{
				displayName: 'Autocomplete Template (JSON)',
				name: 'autocomplete_template',
				type: 'json',
				default: '{}',
				description: 'Questionnaire form shown when a document is created from this template',
				routing: { send: { type: 'body', property: 'autocomplete_template' } },
			},
			{
				displayName: 'Autoshow',
				name: 'autoshow',
				type: 'boolean',
				default: false,
				description: 'Whether to auto-show in patient portal on the first login (administrative only)',
				routing: { send: { type: 'body', property: 'autoshow' } },
			},
			{
				displayName: 'Display in Consultations',
				name: 'display_in_consultations',
				type: 'boolean',
				default: false,
				description: 'Whether to show as a column in treatment group table (administrative only)',
				routing: { send: { type: 'body', property: 'display_in_consultations' } },
			},
			{
				displayName: 'Doctor ID',
				name: 'doctor',
				type: 'string',
				default: '',
				description: 'Doctor ID from the clinic; when set, quotes and invoices created from this template are accounted under that provider',
				routing: { send: { type: 'body', property: 'doctor' } },
			},
			{
				displayName: 'Intro Text',
				name: 'intro_text',
				type: 'string',
				default: '',
				description: 'Optional introductory text for the document',
				routing: { send: { type: 'body', property: 'intro_text' } },
			},
			{
				displayName: 'Master Template ID',
				name: 'master',
				type: 'string',
				default: '',
				description: 'Master invoice document template ID for deposit invoice or credit note',
				routing: { send: { type: 'body', property: 'master' } },
			},
			{
				displayName: 'Template Texts (JSON)',
				name: 'template_texts',
				type: 'json',
				default: '[]',
				description: 'Array of { name, content } objects for reusable template snippets',
				routing: { send: { type: 'body', property: 'template_texts' } },
			},
		],
	},
];
