import type { INodeProperties } from 'n8n-workflow';

const showOnlyForDoctorCreate = {
	operation: ['create'],
	resource: ['doctor'],
};

export const doctorCreateDescription: INodeProperties[] = [
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'name@email.com',
		default: '',
		required: true,
		displayOptions: { show: showOnlyForDoctorCreate },
		description: "Collaborator's email address (login)",
		routing: { send: { type: 'body', property: 'email' } },
	},
	{
		displayName: 'Role',
		name: 'kind',
		type: 'options',
		options: [
			{ name: 'Assistant', value: 11 },
			{ name: 'Dietician', value: 8 },
			{ name: 'Doctor', value: 10 },
			{ name: 'Manager', value: 12 },
			{ name: 'Owner', value: 13 },
			{ name: 'Regular Executive', value: 5 },
			{ name: 'Secretary', value: 9 },
		],
		default: 10,
		required: true,
		displayOptions: { show: showOnlyForDoctorCreate },
		description: 'Collaborator role at the clinic',
		routing: { send: { type: 'body', property: 'kind' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: showOnlyForDoctorCreate },
		options: [
			{
				displayName: 'Activate Online Booking',
				name: 'activate_online_booking',
				type: 'boolean',
				default: false,
				description: 'Whether online booking is allowed for this collaborator',
				routing: { send: { type: 'body', property: 'activate_online_booking' } },
			},
			{
				displayName: 'Color',
				name: 'color',
				type: 'color',
				default: '',
				placeholder: 'ffffffff',
				description: 'RGBA HEX color code used to display the collaborator in the calendar',
				routing: { send: { type: 'body', property: 'color' } },
			},
			{
				displayName: 'Display in Calendar',
				name: 'display_in_calendar_provider_view',
				type: 'boolean',
				default: true,
				description: 'Whether the collaborator appears as a provider in calendar view',
				routing: { send: { type: 'body', property: 'display_in_calendar_provider_view' } },
			},
			{
				displayName: 'First Name',
				name: 'first_name',
				type: 'string',
				default: '',
				description: "Collaborator's first name",
				routing: { send: { type: 'body', property: 'first_name' } },
			},
			{
				displayName: 'Last Name',
				name: 'last_name',
				type: 'string',
				default: '',
				description: "Collaborator's last name",
				routing: { send: { type: 'body', property: 'last_name' } },
			},
			{
				displayName: 'Speciality',
				name: 'speciality',
				type: 'options',
				options: [
					{ name: 'Aesthetic Doctor', value: 'aesthetic_doctor' },
					{ name: 'Anesthesiologist', value: 'anesthesiologist' },
					{ name: 'Assistant', value: 'assistant' },
					{ name: 'Beautician', value: 'beautician' },
					{ name: 'Clinic Manager', value: 'clinic_manager' },
					{ name: 'Clinic Owner', value: 'clinic_owner' },
					{ name: 'Clinic Team Member', value: 'clinic_team_member' },
					{ name: 'Dental Surgeon', value: 'dental_surgeon' },
					{ name: 'Dermatologist', value: 'dermatologist' },
					{ name: 'Dietician', value: 'dietician' },
					{ name: 'Injecting Nurse', value: 'injecting_nurse' },
					{ name: 'Other', value: 'other_surgeon' },
					{ name: 'Plastic Surgeon', value: 'plastic_surgeon' },
				],
				default: 'aesthetic_doctor',
				description: 'Medical speciality for this collaborator',
				routing: { send: { type: 'body', property: 'speciality' } },
			},
		],
	},
];
