import type { INodeProperties } from 'n8n-workflow';

const showOnlyForDoctorUpdate = {
	operation: ['update'],
	resource: ['doctor'],
};

export const doctorUpdateDescription: INodeProperties[] = [
	{
		displayName: 'Speciality',
		name: 'speciality',
		type: 'options',
		options: [
			{ name: 'Aesthetic Doctor', value: 'aesthetic_doctor' },
			{ name: 'Anesthesiologist', value: 'anesthesiologist' },
			{ name: 'Assistant', value: 'assistant' },
			{ name: 'Beautician', value: 'beautician' },
			{ name: 'Clinic Manager', value: 'clinic_manager' },
			{ name: 'Clinic Owner', value: 'clinic_owner' },
			{ name: 'Clinic Team Member', value: 'clinic_team_member' },
			{ name: 'Dental Surgeon', value: 'dental_surgeon' },
			{ name: 'Dermatologist', value: 'dermatologist' },
			{ name: 'Dietician', value: 'dietician' },
			{ name: 'Injecting Nurse', value: 'injecting_nurse' },
			{ name: 'Other', value: 'other_surgeon' },
			{ name: 'Plastic Surgeon', value: 'plastic_surgeon' },
		],
		default: 'aesthetic_doctor',
		required: true,
		displayOptions: { show: showOnlyForDoctorUpdate },
		description: 'Medical speciality for this collaborator',
		routing: { send: { type: 'body', property: 'speciality' } },
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: showOnlyForDoctorUpdate },
		options: [
			{
				displayName: 'Activate Online Booking',
				name: 'activate_online_booking',
				type: 'boolean',
				default: false,
				routing: { send: { type: 'body', property: 'activate_online_booking' } },
			},
			{
				displayName: 'Color',
				name: 'color',
				type: 'color',
				default: '',
				placeholder: 'ffffffff',
				routing: { send: { type: 'body', property: 'color' } },
			},
			{
				displayName: 'Display in Calendar',
				name: 'display_in_calendar_provider_view',
				type: 'boolean',
				default: true,
				routing: { send: { type: 'body', property: 'display_in_calendar_provider_view' } },
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				routing: { send: { type: 'body', property: 'email' } },
			},
			{
				displayName: 'First Name',
				name: 'first_name',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'first_name' } },
			},
			{
				displayName: 'Last Name',
				name: 'last_name',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'last_name' } },
			},
			{
				displayName: 'Role',
				name: 'kind',
				type: 'options',
				options: [
					{ name: 'Assistant', value: 11 },
					{ name: 'Dietician', value: 8 },
					{ name: 'Doctor', value: 10 },
					{ name: 'Manager', value: 12 },
					{ name: 'Owner', value: 13 },
					{ name: 'Regular Executive', value: 5 },
					{ name: 'Secretary', value: 9 },
				],
				default: 10,
				routing: { send: { type: 'body', property: 'kind' } },
			},
		],
	},
];
