import type { INodeProperties } from 'n8n-workflow';

const showOnlyForVisitTypeCreate = {
	operation: ['create'],
	resource: ['visitType'],
};

export const visitTypeCreateDescription: INodeProperties[] = [
	{
		displayName: 'Subject',
		name: 'subject',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: showOnlyForVisitTypeCreate },
		description: 'Display name of the visit type',
		routing: { send: { type: 'body', property: 'subject' } },
	},
	{
		displayName: 'Color',
		name: 'color',
		type: 'color',
		default: 'ffffffff',
		required: true,
		placeholder: 'ffffffff',
		displayOptions: { show: showOnlyForVisitTypeCreate },
		description: 'Hex color for the visit type (e.g. FEC0CB)',
		routing: { send: { type: 'body', property: 'color' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: showOnlyForVisitTypeCreate },
		options: [
			{
				displayName: 'Bolt Note ID',
				name: 'bolt_note',
				type: 'string',
				default: '',
				description: 'Bolt note (survey form) ID',
				routing: { send: { type: 'body', property: 'bolt_note' } },
			},
			{
				displayName: 'Category ID',
				name: 'category',
				type: 'string',
				default: '',
				description: 'Visit type category ID',
				routing: { send: { type: 'body', property: 'category' } },
			},
			{
				displayName: 'Display in Agenda',
				name: 'display_in_agenda',
				type: 'boolean',
				default: true,
				description: 'Whether to show this visit type in the agenda',
				routing: { send: { type: 'body', property: 'display_in_agenda' } },
			},
			{
				displayName: 'Display in Appointment Form',
				name: 'display_in_appointment_form',
				type: 'boolean',
				default: true,
				description: 'Whether to show this visit type in the appointment form',
				routing: { send: { type: 'body', property: 'display_in_appointment_form' } },
			},
			{
				displayName: 'Display in Dashboard',
				name: 'display_in_dashboard',
				type: 'boolean',
				default: true,
				description: 'Whether to show this visit type in the dashboard',
				routing: { send: { type: 'body', property: 'display_in_dashboard' } },
			},
			{
				displayName: 'Display in Patient File',
				name: 'display_in_patient_file',
				type: 'boolean',
				default: true,
				description: 'Whether to show this visit type in the patient file visit create form',
				routing: { send: { type: 'body', property: 'display_in_patient_file' } },
			},
			{
				displayName: 'Duration (Minutes)',
				name: 'duration_minutes',
				type: 'number',
				default: 30,
				typeOptions: { minValue: 0 },
				description: 'Default duration in minutes',
				routing: { send: { type: 'body', property: 'duration_minutes' } },
			},
			{
				displayName: 'Enable Treatment Pre-Payments',
				name: 'enable_treatment_pre_payments',
				type: 'boolean',
				default: false,
				description: 'Whether to allow pre-payment for treatments',
				routing: { send: { type: 'body', property: 'enable_treatment_pre_payments' } },
			},
			{
				displayName: 'Next Visit Reminder (Days)',
				name: 'next_visit_reminder_days',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Days after visit to trigger next visit reminder (0 to disable)',
				routing: { send: { type: 'body', property: 'next_visit_reminder_days' } },
			},
			{
				displayName: 'Price',
				name: 'price',
				type: 'string',
				default: '',
				description: 'Default price',
				routing: { send: { type: 'body', property: 'price' } },
			},
		],
	},
];
